import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";



const roboto = Roboto({
  subsets: ['latin'], 
  weight: ['400', '700'],
  variable: '--font-roboto', 
  display: 'swap', 
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
      title: "Create Next App",
      description: "Generated by create next app",
      url: `https://notehub.com/notes/`,
      siteName: 'NoteHub',
      images: [
        {
          url: 'https://ac.goit.global/fullstack/react/notehub-og-meta.jpg',
          width: 1200,
          height: 630,
          alt:  "Create Next App",
        },
      ],
      type: 'article',
    },
  
};

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
   modal:  React.ReactNode;
 
}>) {
  return (
    <html lang="en">
    
      <body className={`${roboto.variable}`}>
        <TanStackProvider>
          <Header />
          <>
        {children}
          {modal}
          </>
        <Footer/>
        </TanStackProvider>
      </body>
    </html>
  );
}
